const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('csapi', {
  getInitial: () => ipcRenderer.invoke('get:initial'),
  onData: (cb) => ipcRenderer.on('push:data', (e, p) => cb(p)),
  onRefreshDenied: (cb) => ipcRenderer.on('push:refresh-denied', (e, p) => cb(p)),
  onStreamers: (cb) => ipcRenderer.on('push:streamers', (e, v) => cb(v)),
  onUpdDialog: (cb) => ipcRenderer.on('push:upd-dialog', (e, v) => cb(v)),
  onSettings: (cb) => ipcRenderer.on('push:settings', (e, s) => cb(s)),
  onMini: (cb) => ipcRenderer.on('push:mini', (e, m) => cb(m)),
  onLocked: (cb) => ipcRenderer.on('push:locked', (e, l) => cb(l)),
  onFocus: (cb) => ipcRenderer.on('push:focus', (e, f) => cb(f)),
  onGlassFrame: (cb) => ipcRenderer.on('glass-frame', (e, url) => cb(url)),
  glassFallback: () => ipcRenderer.send('glass-fallback'),
  refresh: () => ipcRenderer.send('refresh'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  checkUpdate: () => ipcRenderer.invoke('upd:check'),
  installUpdate: () => ipcRenderer.invoke('upd:install'),
  applyUpdate: () => ipcRenderer.invoke('upd:apply'),
  onUpdDl: (cb) => ipcRenderer.on('push:upd-dl', (e, v) => cb(v)),
  hide: () => ipcRenderer.send('win:hide'),
  setMini: (m) => ipcRenderer.send('set:mini', m),
  setSize: (p) => ipcRenderer.send('set:size', p),
  setSetting: (kv) => ipcRenderer.send('set:setting', kv),
  transfersSeen: () => ipcRenderer.send('transfers-seen'),
  unlock: () => ipcRenderer.send('unlock'),
  quit: () => ipcRenderer.send('app:quit'),
  // 关注(高光选手/队伍)
  searchPlayers: (q) => ipcRenderer.invoke('search:players', q),
  starAddPlayer: (p) => ipcRenderer.invoke('star:add-player', p),
  starRemovePlayer: (id) => ipcRenderer.send('star:remove-player', id),
  starAddTeam: (t) => ipcRenderer.invoke('star:add-team', t),
  starRemoveTeam: (id) => ipcRenderer.send('star:remove-team', id),
  copyText: (t) => ipcRenderer.invoke('copy-text', t),
  setPanda: (token) => ipcRenderer.invoke('set:panda', token),
  setTwitch: (v) => ipcRenderer.invoke('set:twitch', v),
});
